---
version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.4
    platform: linux/amd64
    restart: on-failure
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:6.2.4
    platform: linux/amd64
    restart: on-failure
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

#  schema-registry:
#    image: confluentinc/cp-schema-registry:6.2.4
#    platform: linux/amd64
#    restart: on-failure
#    hostname: schema-registry
#    container_name: schema-registry
#    depends_on:
#      - broker
#    ports:
#      - "8081:8081"
#    environment:
#      SCHEMA_REGISTRY_HOST_NAME: schema-registry
#      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:9092'

  datagen-1:
    build: .
    container_name: datagen-1
    restart: on-failure
    image: kafka-streams-stateful-rebalance-idle-group-members
    command: ["sh", "-c", "java -noverify -cp /app/app.jar io.confluent.developer.KafkaProducerApplication config.properties random-strings-1"]
    environment:
      CLIENT_ID: datagen-1
      BATCH_SIZE: 500
      BATCH_SCHEDULE_MS: 500
    depends_on:
      - broker

  datagen-2:
    build: .
    container_name: datagen-2
    restart: on-failure
    image: kafka-streams-stateful-rebalance-idle-group-members
    command: ["sh", "-c", "java -noverify -cp /app/app.jar io.confluent.developer.KafkaProducerApplication config.properties random-strings-2"]
    environment:
      CLIENT_ID: datagen-1
      BATCH_SIZE: 500
      BATCH_SCHEDULE_MS: 500
    depends_on:
      - broker

  app-1:
    build: .
    container_name: app-1
    restart: on-failure
    image: kafka-streams-stateful-rebalance-idle-group-members
    depends_on:
      - broker

  app-2:
    build: .
    container_name: app-2
    restart: on-failure
    image: kafka-streams-stateful-rebalance-idle-group-members
    depends_on:
      - broker

  app-3:
    build: .
    container_name: app-3
    restart: on-failure
    image: kafka-streams-stateful-rebalance-idle-group-members
    depends_on:
      - broker

  app-4:
    build: .
    container_name: app-4
    restart: on-failure
    image: kafka-streams-stateful-rebalance-idle-group-members
    depends_on:
      - broker

  app-5:
    build: .
    container_name: app-5
    restart: on-failure
    image: kafka-streams-stateful-rebalance-idle-group-members
    depends_on:
      - broker

  app-6:
    build: .
    container_name: app-6
    restart: on-failure
    image: kafka-streams-stateful-rebalance-idle-group-members
    depends_on:
      - broker